In [8]:
import numpy as np
import math

In [5]:
X = np.array([[34.62365962 ,78.02469282],
 [30.28671077, 43.89499752],
 [35.84740877 ,72.90219803],
 [60.18259939 ,86.3085521 ],
 [79.03273605 ,75.34437644],
 [45.08327748 ,56.31637178],
 [61.10666454 ,96.51142588],
 [75.02474557 ,46.55401354],
 [76.0987867  ,87.42056972],
 [84.43281996 ,43.53339331]])

print(X)

[[34.62365962 78.02469282]
 [30.28671077 43.89499752]
 [35.84740877 72.90219803]
 [60.18259939 86.3085521 ]
 [79.03273605 75.34437644]
 [45.08327748 56.31637178]
 [61.10666454 96.51142588]
 [75.02474557 46.55401354]
 [76.0987867  87.42056972]
 [84.43281996 43.53339331]]


In [6]:
y = np.array([0., 0., 0., 1., 1., 0., 1., 1., 1., 1.]);
print(y)

[0. 0. 0. 1. 1. 0. 1. 1. 1. 1.]


$$sigmoid(z) = \frac{1}{1 + e^{-z}}$$

In [7]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

now we will implement the cost function :
$$ J(\mathbf{w},b) = \frac{1}{m}\sum_{i=0}^{m-1} \left[ loss(f_{\mathbf{w},b}(\mathbf{x}^{(i)}), y^{(i)}) \right] \tag{1}$$


The $loss$ function for logistic regression is :
$$loss(f_{\mathbf{w},b}(\mathbf{x}^{(i)}), y^{(i)}) = (-y^{(i)} \log\left(f_{\mathbf{w},b}\left( \mathbf{x}^{(i)} \right) \right) - \left( 1 - y^{(i)}\right) \log \left( 1 - f_{\mathbf{w},b}\left( \mathbf{x}^{(i)} \right) \right) \tag{2}$$



In [9]:
def f(x , w, b):
    return sigmoid(np.dot(x , w) + b)

def compute_loss(x , y , w , b):
    return -y * math.log(f(x , w , b)) - (1-  y) * math.log(1 - f(x , w, b))

def compute_cost(X, y, w, b, *argv):
    m, n = X.shape
    
    total_cost = 0
    
    for i in range(m):
        total_cost += compute_loss(X[i] , y[i] , w , b)
        
    total_cost /= m

    return total_cost


The gredient descent algorithm for logistic regression : 
$$\begin{align*}& \text{repeat until convergence:} \; \lbrace \newline \; & b := b - \alpha \frac{\partial J(\mathbf{w},b)}{\partial b} \newline \; & w_j := w_j - \alpha \frac{\partial J(\mathbf{w},b)}{\partial w_j} \tag{1} \; & \text{for j := 0..n-1}\newline & \rbrace\end{align*}$$


To implement gredient descent, we will implement a function to compute the following terms :

$$\frac{\partial J(\mathbf{w},b)}{\partial w}, \frac{\partial J(\mathbf{w},b)}{\partial b}$$

$$ \frac{\partial J(\mathbf{w},b)}{\partial b} = \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - \mathbf{y}^{(i)}) \tag{2} $$ $$ \frac{\partial J(\mathbf{w},b)}{\partial w_j} = \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - \mathbf{y}^{(i)})x_{j}^{(i)} \tag{3} $$

In [27]:
def compute_gradient(X, y, w, b): 
    m, n = X.shape
    dj_dw = np.zeros(w.shape)
    dj_db = 0.
    for i in range(m):
        err = f(X[i] , w , b) - y[i]
        dj_db += err
        for j in range(n):
            dj_dw[j] += err * X[i, j]
    dj_dw /= m
    dj_db /= m
        
    return dj_db, dj_dw

Since we implemented all gredient descent components, we're ready now to implement the algorithm itself.

In [28]:
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters): 
    
    # number of training examples
    m = len(X)
    
    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        dj_db, dj_dw = gradient_function(X, y, w_in, b_in)   

        # Update Parameters using w, b, alpha and gradient
        w_in = w_in - alpha * dj_dw               
        b_in = b_in - alpha * dj_db              
        
    return w_in, b_in

In [30]:
#assume initial values of w , b

initial_w = 0.01 * (np.random.rand(2) - 0.5)
initial_b = -8
iterations = 10000
alpha = 0.001

w , b = gradient_descent(X , y , initial_w , initial_b , compute_cost , compute_gradient , alpha , iterations)



Now we can evaluate the logistic regression.

using the learned values of $w,b$ we can predict whether data entered has a value of 0 or 1.

if $f(x^{(i)}) >= 0.5$, predict $y^{(i)}=1$
 
  if $f(x^{(i)}) < 0.5$, predict $y^{(i)}=0$
    

In [31]:
def predict(X, w, b): 
    m, n = X.shape   
    p = np.zeros(m)
    for i in range(m):
        p[i] = f(X[i] , w , b) >= 0.5
    return p

In [32]:
#test predict function
np.random.seed(1)
tmp_w = np.random.randn(2)
tmp_b = 0.3    
tmp_X = np.random.randn(4, 2) - 0.5

tmp_p = predict(tmp_X, tmp_w, tmp_b)
print(tmp_p)
#output = [0. 1. 1. 1.]

[0. 1. 1. 1.]
